gappih=8
gappiv=8
gappoh=8
gappov=8

borderpx=0
border_radius=10

cursor_theme=Bibata-Modern-Ice
cursor_size=24

animation_duration_open=200
animation_duration_close=200
animation_duration_move=200
animation_duration_tag=200

drag_tile_to_tile=1
drag_tile_small=0

focus_cross_monitor=1
exchange_cross_monitor=1 # doesn't work for some reason
new_is_master=0
