# GIGA-BYTE M27Q (left)
monitorrule=model:M27Q,width:2560,height:1440,refresh:169.831,x:0,y:0,scale:1,vrr:1

# ViewSonic XG2401 (right)
monitorrule=model:XG2401 SERIES,width:1920,height:1080,refresh:143.766,x:2560,y:128,scale:1
