# === Environment ===
env=CONFIG_TERMINAL_APP,ghostty
env=CONFIG_BROWSER_APP,zen-beta
env=CONIFG_COLOR_PICKER_APP,dms color pick -a
env=CONFIG_SCREENSHOT_APP,dms screenshot --no-file
env=CONFIG_SCREENSHOT_EDIT_APP,dms screenshot --stdout | satty -f -
env=CONFIG_APP_LAUNCHER,dms ipc call spotlight toggle
env=CONFIG_CONTROL_CENTER_APP,missioncenter
env=CONFIG_CLIPBOARD_HISTORY_APP,dms ipc call clipboard toggle
env=CONFIG_FILE_MANAGER_APP,nautilus

env=DMS_SCREENSHOT_EDITOR,satty

env=XDG_CURRENT_DESKTOP,gnome
env=XDG_SESSION_TYPE,wayland

env=__GL_GSYNC_ALLOWED,1
env=__GL_VRR_ALLOWED,1
env=LIBVA_DRIVER_NAME,nvidia
env=__GLX_VENDOR_LIBRARY_NAME,nvidia
env=ELECTRON_OZONE_PLATFORM_HINT,auto
env=NVD_BACKEND,direct
env=GBM_BACKEND,nvidia-drm
env=WLR_NO_HARDWARE_CURSORS,1

# === Autostart ===
exec-once=dms restart

# === Includes ===
source=./modules/input.conf
source=./modules/look.conf

source-optional=./dms/outputs.conf
