# === Environment ===
env=XDG_CURRENT_DESKTOP,gnome
env=XDG_SESSION_TYPE,wayland

env=__GL_GSYNC_ALLOWED,1
env=__GL_VRR_ALLOWED,1
env=LIBVA_DRIVER_NAME,nvidia
env=__GLX_VENDOR_LIBRARY_NAME,nvidia
env=ELECTRON_OZONE_PLATFORM_HINT,auto
env=NVD_BACKEND,direct
env=GBM_BACKEND,nvidia-drm
env=WLR_NO_HARDWARE_CURSORS,1

# === Autostart ===
exec-once=noctalia-shell

# === Includes ===
source=./modules/input.conf
source=./modules/look.conf

source-optional=./dms/outputs.conf
