# === Environment ===
env=XDG_CURRENT_DESKTOP,gnome
env=XDG_SESSION_TYPE,wayland

env=ELECTRON_OZONE_PLATFORM_HINT,auto

# === Autostart ===
exec-once=noctalia-shell

# === Includes ===
source=./modules/input.conf
source=./modules/look.conf

source-optional=./dms/outputs.conf
