line-height = 1.2
confirm-before-quit = false

[shell]
program = "pwsh"
args = ["-NoExit", "-Command", "Set-Location -Path $HOME"]

[editor]
program = "nvim"
args = []

[colors]
# Background and foreground
background = '#15161B'
foreground = '#FFFFFF'

# Cursor colors
cursor = '#ffdb29'
cursor-foreground = '#000000'

# Selection colors
selection-background = '#264F78'
selection-foreground = '#ffffff'

# Normal colors (0-7)
black = '#2e3339'
red = '#FF5555'
green = '#95FB79'
yellow = '#FFEE99'
blue = '#82AAFF'
magenta = '#D2A6FF'
cyan = '#82AAFF'
white = '#FFFFFF'

# Bright colors (8-15)
bright-black = '#49525c'
bright-red = '#ff5d5d'
bright-green = '#a3ff85'
bright-yellow = '#ffffa8'
bright-blue = '#8fbbff'
bright-magenta = '#e7b6ff'
bright-cyan = '#8fbbff'
bright-white = '#ffffff'

# Dim colors
dim-black = '#1b1e22'
dim-red = '#e54c4c'
dim-green = '#86e16c'
dim-yellow = '#e5d689'
dim-blue = '#7599e5'
dim-magenta = '#bd95e5'
dim-cyan = '#7599e5'
dim-white = '#e5e5e5'

[fonts]
size = 22
family = "CaskaydiaCove Nerd Font"

[window]
width = 1900
height = 1000
