#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "=== Arch Linux Setup ==="
echo "This will install and configure your system in stages."
echo ""

source "$SCRIPT_DIR/scripts/system.sh"
source "$SCRIPT_DIR/scripts/dev.sh"
source "$SCRIPT_DIR/scripts/gaming.sh"
source "$SCRIPT_DIR/scripts/shell.sh"
source "$SCRIPT_DIR/scripts/assets.sh"

echo -e "\n✓ Setup complete!"
echo ""
echo "Next steps:"
echo ""
echo "  dotbot -c linux.install.yaml"
echo "  ================================================"
echo "  Configure prompt:"
echo "      tide configure"
echo "  ================================================"
echo "  Git:"
echo "      gh auth login"
echo "      git config --global user.name 'Your Name'"
echo "      git config --global user.email 'your@email.com'"
echo "  ================================================"
echo "  Desktop:"
echo "      nwg-displays"
echo "      nwg-look"
echo "  ================================================"
echo "  Bar:"
echo "      curl -fsSL https://install.danklinux.com | sh"
